version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - ALLOWED_HOSTS=*
    volumes:
      - ./static:/app/static:ro
    env_file:
      - ../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"] 
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: frontend
      args:
        - REACT_APP_API_URL=http://example.com:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: ai-newssense